config/routes.rb
MaximusSamurai::Application.routes.draw do

  devise_for :views

	match 'events/:id/supplemental_info' => 'events#supplemental_info'
	match 'events/:id/supplmenetal_info/edit' => 'events#edit_supplemental_info'
	match 'events/:id/change_location' => 'events#edit_location'
	get 'events/:id/description', :to => 'events#description'
	get 'events/:id/group_email', :to => 'events#group_email'
	get 'events/:id/send_group_email', :to => 'events#send_group_email'
	get 'events/:id/email_host', :to => 'events#email_host'
	get 'events/:id/send_host_email', :to => 'events#send_host_email'
	get 'events/:id/taken_items', :to=>'events#taken_items'
	get 'events/:id/available_items', :to=>'events#available_items'
	get 'events/:id/guests', :to => 'events#guests'
	get 'events/:id/potluck_statistics', :to => 'events#potluck_statistics'
	get 'events/:id/get_host_groups', :to => 'events#get_host_groups'
	delete 'events/:id/remove_from_event/:user_id', :to => 'events#remove_from_event'
	get 'users/:user_id/groups(.:format)', :to => 'groups#index'
	post 'users/:user_id/groups(.:format)',:to => 'groups#create'
	get  'users/:user_id/groups/new(.:format)', :to => 'groups#new'
	get 'users/:user_id/groups/:id(.:format)', :to => 'groups#show'
	get 'users/:user_id/groups/:id/edit(.:format)', :to => 'groups#edit'
	put 'users/:user_id/groups/:id(.:format)', :to => 'groups#update'
	delete 'users/:user_id/groups/:id(.:format)', :to => 'groups#destroy'
	get '/faq', :to => 'events#faq'
	put 'events/:id/change_roles/:attendee_id(.:format)', :to => 'events#change_roles'
	get 'events/:id/export_remaining_items', :to => 'events#export_remaining_items'
	get 'users/:user_id/event_settings(.:format)', :to => 'event_settings#get_settings'
	put 'users/:user_id/event_settings/:id(.:format)', :to => 'event_settings#update_event_settings'
	get '/thank_you', :to => 'attendees#thank_you'

	resources :events do
		get 'attendees/add_attendees', :to => 'attendees#add_attendees'
		post 'attendees/invite_guests', :to => 'attendees#invite_guests'
		get 'attendees/other_guests', :to => 'attendees#other_guests'
		get 'attendees/send_updated_calendar', :to => 'attendees#send_updated_calendar'
		get 'attendees/rsvp', :to => 'attendees#rsvp'
		get 'attendees/:id/send_calendar', :to => 'attendees#send_individual_calendar'
		get 'attendees/:id/email_guest', :to => "attendees#email_guest"
		get 'attendees/:id/send_guest_email', :to => "attendees#send_guest_email"
		get 'suggestions/:id/approve', :to => "suggestions#approve"
		get 'suggestions/:id/reject', :to => "suggestions#reject"
		resources :attendees 
		resources :potluck_items
		resources :suggestions
  end

  devise_for :users
	devise_for :attendees

   root :to => 'events#index'

	devise_scope :user do
  	get "/", :to => 'devise/sessions#new'
  end

end

app/models/potluck_item.rb
require 'csv'
class PotluckItem < ActiveRecord::Base
	belongs_to :event

	before_validation do |potluck_item|
		potluck_item.dishes = JSON.parse(potluck_item.dishes) unless potluck_item.dishes.is_a?(Array)
	end

	before_destroy do |potluck_item|
		return false unless potluck_item.taken_items.empty?
	end

	validates :event_id, :category, :host_quantity, :presence => true
	validates :host_quantity, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
	validates :category, :uniqueness => { :scope => :event_id, :message => "should be unique per event" }
	validate :verify_no_duplicates_dishes
	validate :verify_taken_item_still_present_in_available_list
	validate :verify_that_item_quantity_is_not_less_than_zero

	attr_accessible :event_id, :category, :dishes, :host_quantity, :taken_items
	serialize :dishes, Array
	serialize :taken_items, Array

	def remove_dish_from_list(dish, attendee_id)
		index_for_available_item = self.dishes.find_index(dish)
		taken_item_object = {"id" => attendee_id, "item" => dish}
		self.taken_items << taken_item_object
		self.dishes.delete_at(index_for_available_item)
		self.save
	end

	def make_item_available(dish, attendee_id)
		item_index = self.taken_items.find_index({"id"=> attendee_id, "item"=> dish})
		self.dishes << dish
		self.taken_items.delete_at(item_index)
		self.save
	end

	def initialize_taken_items
		if self.taken_items.blank?
			self.taken_items = []
		end
	end

	# Returns a list of unapplied deltas that must be rolledback from guests rsvp before saving
	def self.mergeDeltasAndUpdateIfNecessary(deltas_list, event, guest_id)
		grouped_deltas = deltas_list.group_by{ |x| x["category"] }
		unapplied_deltas = []
		grouped_deltas.each do |category, item_list|
			potluck_item = event.potluck_items.where("category = ?", category).first
			available_items = potluck_item.dishes
			taken_items = potluck_item.taken_items
			item_list.each do |item_hash|
				item_index = available_items.index{ |a| a["item"].eql?(item_hash["item"]) }
				item = available_items.at(item_index)
				if (item["quantity"] - item_hash["quantity"]) >= 0
					item["quantity"] = item["quantity"] - item_hash["quantity"]
					taken_index = taken_items.index{ |x| x["item"].eql?(item_hash["item"]) }
					if item_hash["removed"] #remove person from taken_list
						rsvped_item = potluck_item.taken_items.at(taken_index)
						rsvped_item["guests"].delete(guest_id)
						if rsvped_item["guests"].blank? #remove it from the taken_index
							potluck_item.taken_items.delete_if { |x| x["item"].eql?(item_hash["item"]) }
						end
					else  #add person to the taken_items list
						if taken_index.blank? #if first one to rsvp, add it
							potluck_item.taken_items << {"item" => item_hash["item"], "guests" => [guest_id]}
						else #add guest id to "guests" array (if not already in there)
							rsvped_item = potluck_item.taken_items.at(taken_index)
							unless rsvped_item["guests"].include?(guest_id)
								rsvped_item["guests"] << guest_id
							end
						end
					end
				else
					unapplied_deltas << item_hash
				end
			end
			potluck_item.save
		end
		unapplied_deltas
	end

	def self.make_items_available(guest, event)
		groupedBy_list = guest.dish.select{|x| x["is_custom"] == false }.group_by{ |x| x["category"] }
		groupedBy_list.each do |key, lists|
			potluck_item = PotluckItem.where('event_id = ? and category = ?', event.id, key).first
			lists.each do |iterItem|
				item_index = potluck_item.dishes.index{|x| x["item"].eql?(iterItem["item"]) }
				item = potluck_item.dishes.at(item_index)
				item["quantity"] = item["quantity"] + iterItem["quantity"]
				taken_index = potluck_item.taken_items.index { |x| x["item"].eql?(iterItem["item"]) }
				taken_item = potluck_item.taken_items.at(taken_index)
				taken_item["guests"].delete(guest.id)
				if taken_item["guests"].blank?
					potluck_item.taken_items.delete_at(taken_index)
				end
			end
			potluck_item.save
		end
	end

	def self.export_remaining_lists_from(potluck_items)
		available_items = potluck_items.select{|item| item.dishes.count > 0}.map{|item| [item.category, item.dishes] }
		CSV.generate do |csv|
			csv << ["Category","Item","Quantity"]
			available_items.each do |category_item|
				category = category_item[0]
				category_item[1].each do |item|
					unless item["quantity"] == 0
						csv << [category, item["item"],item["quantity"]]
					end
				end
			end
		end
	end

	def verify_no_duplicates_dishes
		available_items = self.dishes.map{|a| a["item"]}
		errors.add(:dishes, "No duplicates allowed in list") unless available_items.uniq.length == available_items.length
	end

	def verify_taken_item_still_present_in_available_list
		self.taken_items.each do |item|
			errors.add(:dishes, "Cannot remove item from available selection since someone has RSVPed with it. You must remove it from that guest first before you can remove it") unless taken_items.blank? || !self.dishes.index{|x| x["item"].eql?(item["item"])}.blank?
		end
	end

	def verify_that_item_quantity_is_not_less_than_zero
		errors.add(:dishes, "Item quantity cannot be less than zero") unless self.dishes.blank? || self.dishes.find_all{ |x| x["quantity"] >= 0 }.count == self.dishes.count
	end

	def self.build_from_suggestion(suggestion)
		transformed_suggestions = suggestion.suggested_items.map{|suggestion| {"item" => suggestion, "quantity" => 1} }
		if suggestion.new_or_existing.eql?("New")
			return PotluckItem.new(:event_id => suggestion.event_id, :category => suggestion.category, :dishes => transformed_suggestions, :host_quantity => 1)
		else
			potluck_item = suggestion.event.potluck_items.find{|item| item.category.eql?(suggestion.category)}
			potluck_item.dishes |= transformed_suggestions
			return potluck_item
		end
	end
end

app/models/potluckitems.rb
class Potluckitems


		DEFAULT_POTLUCK_LIST = {"apps" => ["Six Layer Dip","Quacamole","Salsa","Tortilla Chips","Jumbo Shrimp Cocktail","Artichoke Dip","Mexican Cheese Dip","Chili Cheese Dip","Hummus","Bite-sized Pizzas","Mac and Cheese Bites","Ahi Tuna Poke","Loaded Jalapeno Poppers","Stuffed Mushrooms","Fried Mozzarella Sticks","Beef Taquitos","Spring Rolls","Egg Rolls","Loaded Nachos","Caprese Toasts","Pigs in a Blanket","Veggie Platter","Pulled Pork Sliders","Buffalo Wings","Chicken Tenders"],"salads" => ["Rainbow Stacked Salad","Potato Salad","Cole Slaw","Pasta Salad","Taco Potato Salad","Fruit Salad"], "main dishes" => ["Make Ahead Fajitas","Pork Ribs","Beef Ribs","Tri Tip","Hot Dogs","Burgers","Kebabs","Thai Chicken Satay","Crunchy Macaroni and Cheese","Spanish Chicken","BLT Rollups","Meatballs","Spaghetti","Pizza","Chicken Chow Mein","Honey Walnut Shrimp","Smoked Salmon","Spanish Chicken","Sicilian One Pot","Honey-baked Ham","Sandwich Platter","Stir Fry","Beef Stroganoff","Meatloaf"], "sides" => ["Scalloped Potatoes","Baked Stuffed Peppers","French Fries","Baked Beans","Popcorn Chicken","Mashed Potatoes w/Gravy","Potato Wedges","Garlic Mashed Potatoes","Sweet Potatoes / Sweet Potato Fries","Kimchi","Garlic Bread"], "desserts" => ["Cobbler","Key Lime Pie","Brownies","Turtle Pie","Cupcakes","Cookies","Pumpkin Pie","Apple Pie","Chocolate Mousse","Block Party Ice Cream Cake","Parfaits","Mini Muffins","Bar Cookies","Cheesecake","Candy","Bread Pudding","Jello","Chocolate Pudding","Eclairs","Cannoli","Funnel Cakes","Fruit Pinwheels","Strudels","Fruit Tart","Dessert Crepes","Scones"] }

end

app/controllers/potluck_items_controller.rb
class PotluckItemsController < ApplicationController
		before_filter :get_event
		before_filter :verify_privileges, :except => [:index]
		before_filter :verify_access, :only => [:index]

  # GET /potluck_items
  # GET /potluck_items.json
  def index
    @potluck_items = @event.potluck_items

    respond_to do |format|
      format.html { render :layout => false }# index.html.erb
      format.json { render json: @event.get_potluck_items_for_guests.to_json }
    end
  end

  # GET /potluck_items/1
  # GET /potluck_items/1.json
  def show
    @potluck_item = PotluckItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @potluck_item }
    end
  end

  # GET /potluck_items/new
  # GET /potluck_items/new.json
  def new
    @potluck_item = PotluckItem.new

    respond_to do |format|
      format.html { render :layout => false }# new.html.erb
      format.json { render json: @potluck_item }
    end
  end

  # GET /potluck_items/1/edit
  def edit
    @potluck_item = PotluckItem.find(params[:id])
		render :layout => false
  end

  # POST /potluck_items
  # POST /potluck_items.json
  def create
    @potluck_item = PotluckItem.new(params[:potluck_item])

    respond_to do |format|
      if @potluck_item.save
        format.html { redirect_to [@event, @potluck_item], notice: 'Potluck item was successfully created.' }
        format.json { render json: @potluck_item, status: :created, location: @potluck_item }
      else
        format.html { render action: "new", status: :unprocessable_entity }
        format.json { render json: @potluck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /potluck_items/1
  # PUT /potluck_items/1.json
  def update
    @potluck_item = PotluckItem.find(params[:id])

    respond_to do |format|
      if @potluck_item.update_attributes(params[:potluck_item])
        format.html { render :action => :show }
        format.json { head :no_content }
      else
        format.html { render action: "edit", status: :unprocessable_entity }
        format.json { render json: @potluck_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /potluck_items/1
  # DELETE /potluck_items/1.json
  def destroy
    @potluck_item = PotluckItem.find(params[:id])

    respond_to do |format|
    	if @potluck_item.destroy
				format.html { render :nothing => true, :status => 204 }
				format.json { head :no_content }
			else
      	format.html { redirect_to event_potluck_items_url }
      	format.json { head :not_acceptable }
			end
    end
  end

	protected

	def get_event
		@event = Event.find(params[:event_id])
	end

	def verify_privileges
		unless current_user && current_user.is_host_for?(@event)
			session[:attendee_id] = nil
			render file: "public/422.html", :layout=>false, :formats => [:html], status: :unprocessable_entity and return
		end
	end

	def verify_access
		if current_user
			unless current_user.is_host_for?(@event) || current_user.belongs_to_event?(@event)
				session[:attendee_id] = nil
				render file: "public/401.html", :layout=>false, :formats => [:html], status: :unauthorized and return
			end
		else
			unless current_attendee.event_id == @event.id
				session[:attendee_id] = nil
				render file: "public/401.html", :layout=>false, :formats => [:html], status: :unauthorized and return
			end
		end
	end

end

app/helpers/potluck_items_helper.rb
module PotluckItemsHelper
end

app/views/potluck_items/_form.html.erb
<%= form_for([@event, @potluck_item]) do |f| %>
  <% if @potluck_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@potluck_item.errors.count, "error") %> prohibited this potluck_item from being saved:</h2>

      <ul>
      <% @potluck_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/potluck_items/_form_new.html.erb
<%= form_for([@event, @potluck_item], :html=>{:id=>"potluckItemsForm"}) do |f| %>
  <% if @potluck_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@potluck_item.errors.count, "error") %> prohibited this potluck_item from being saved:</h2>

      <ul>
      <% @potluck_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<input name="potluck_item[event_id]" id="potluck_item_event_id" type="hidden" value="<%= @event.id %>">

	<p>
	<%= f.label :category %>
	<%= f.text_field :category, :placeholder => "E.g. Appetizers, Games, Misc" %>
	</p>

	<p>
		<%= f.label :host_quantity, 'Desired # of distinct items to be brought' %></a>
		<%= f.text_field :host_quantity, :placeholder => 2 %>
	</p>

	<p>
		<%= f.hidden_field :dishes %>
	</p>

	<% if @potluck_item.id.blank? %>
		<label>Items: </label>
		<textarea id="list_area" rows="5" style="width:100%" placeholder="Create your list via comma-delimited values (ex: bag of chips, jar of salsa, bags of tortillas)" />
	<% else %>
		<% if @potluck_item.dishes.blank? %>
			<div id="list_items">
				<label>Items: </label>
					<div class="list_item">
						<input type="text" class="input-large" id="first_item" placeholder="Box of Twinkies"><input type='text' style="margin-left:1em" class='input-mini' placeholder="2">
					</div>
			</div>
		<% else %>
			<div id="list_items">
				<label>Items: </label>
				<% @potluck_item.dishes.each_with_index do |dish, index| %>
					<div class="list_item">
						<input type='text' class='input-large' value="<%= dish["item"] %>"><input style='margin-left:1em' type='text' class='input-mini' value="<%= dish["quantity"] %>">
						<button class='btn btn-small btn-danger' style='margin-bottom:0.5em;margin-left:0.5em' onclick="$(this.parentElement).remove();"><i class="icon-remove-sign"></i></button>
					</div>
				<% end %>
			</div>
		<% end %>
	<%end %>

  <div>
		<button id="submit_button" class="btn btn-primary">Save</button>
		<% unless @potluck_item.id.blank? %>
			<button id="add_more_items" class="btn btn-success">Add more items</button>
		<% end %>
  </div>
<% end %>

app/views/potluck_items/_list_info.html.erb
<div class="row-fluid">
	<div class="span3 guest-info-body"><%= list_info.category %></div>
	<div class="span4 guest-info-body">
		<ul>
			<% list_info.dishes.each do |dish| %>
				<li><%= dish["item"] %> x <%= dish["quantity"] %></li>
			<% end %>
		</ul>
	</div>
	<div class="span4 guest-info-body">
		<ul>
			<% list_info.taken_items.each do |taken_item| %>
				<li><%= taken_item["item"] %><% unless taken_item["guests"].count == 1 %><%= " [#{taken_item["guests"].count} people]" %><% end %></li>
			<% end %>
		</ul>
	</div>
</div>
<div class="row-fluid">
	<div class="span1 offset3"><%= link_to ' Edit', edit_event_potluck_item_path(event, list_info), { :class=>"editPotluckItems icon-edit" } %>
	</div>
	<div class="span2 offset1"><%= link_to ' Remove', event_potluck_item_path(event, list_info), {confirm: 'Are you sure?', method: :delete, :class=>"removePotluckItems icon-remove"} %>
	</div>
</div>

app/views/potluck_items/edit.html.erb
<div id="flash_notice"><%= flash[:notice] %></div>
<%= render 'form_new' %>
<script>

	$(document).ready(function(){
		$("#add_more_items").click(function(){
			var item_list = $("#list_items");
			var additionalDiv = $("<div class='list_item'></div>");
			var itemText = $("<input type='text' class='input-large' placeholder='Box of Twinkies'>");
			var quantityInput = $("<input type='text' style='margin-left:1em' class='input-mini' placeholder='2'>");
			var removeButton = $("<button class='btn btn-small btn-danger' style='margin-bottom:0.5em;margin-left:0.5em'><i class='icon-remove-sign'></i></button>");
			removeButton.click(function(){
				additionalDiv.remove();
			});
			additionalDiv.appendTo(item_list);
			itemText.appendTo(additionalDiv);
			quantityInput.appendTo(additionalDiv);
			removeButton.appendTo(additionalDiv);
			return false;
		});

		function createPotluckItemObjectFromDiv(itemDiv){
			var item = $.trim($(itemDiv).find(".input-large").val());
			var quantity = $.trim($(itemDiv).find(".input-mini").val());
			if (item.length > 0){
				if ($.isNumeric(quantity) && quantity >= 0)
					return { "item": item, "quantity": parseInt(quantity, 10) };
				else
					return { "item": item, "quantity": 1 };
			}
		}

		$("#submit_button").click(function(){
			var dish_array = [];
			var url = $("#potluckItemsForm").attr('action');
			var serialized_form;

			$("#flash_notice").removeClass("alert alert-error");
			$("#flash_notice").html("");
			dish_array = $.map($(".list_item"), function(itemDiv, index){
					return createPotluckItemObjectFromDiv(itemDiv);
			});

			$("#potluck_item_dishes").val(JSON.stringify(dish_array));

			serialized_form = $("#potluckItemsForm").serialize();
			$.ajax({
				url: url,
				dataType: "html",
				type: "PUT",
				data: serialized_form,
				async: false,
				success: function(data, successText){
					$("#notice").removeClass("alert alert-error alert-success").addClass("alert alert-success");
					$("#notice").html("Items have been updated for this event");
					$("#editPotluckItemModal").modal("hide");
				},
				error: function(){
					console.log("Within error block");
					$("#flash_notice").addClass("alert alert-error");
					$("#flash_notice").html("We couldn't add this potluck category due to the following possible reasons<ul><li>Categories and host quantity need to be present</li><li>Categories need to be unique and items need to be unique per category</li><li>Host quantity needs to be a number</li></ul>");
				}
			});
			return false;
		});

	});

</script>

app/views/potluck_items/index.html.erb
<div class="row-fluid" style="margin-bottom:2em">
	<span class="span3 headers">Category</span>
	<span class="span4 headers">Available Items</span>
	<span class="span4 headers">Taken Items</span>
</div>
<%= render :partial => "list_info", :collection => @event.potluck_items, :locals => {:event => @event, :user => current_user }, :spacer_template => "events/spacer_hr" %>
<br />
<button href="#newPotluckItemModal" id="newPotluckItems" class="btn btn-primary" data-toggle="modal">New Items</button>
<script>
	$(document).ready(function(){

		$("#newPotluckItems").click(function(){
			var url = document.location.pathname+"/potluck_items/new";

			$.ajax({
				url: url,
				dataType: "html",
				success: function(data){
					$("#newPotluckItemModal").find(".modal-body").html(data);
					$("#newPotluckItemModal").modal("show");
				},
				error: function(xhr, errorText, errorObject){
					newPotluckItemModal.find(".modal-body").html("<div class='alert alert-error'>"+errorText+": Cannot retrieve form for new guest. Please contact the administrator about this</div>");
				}
			});
		});

		$(".removePotluckItems").click(function(){
			var url = $(this).attr('href');
			var id = url.substr(url.lastIndexOf("/")+1);
			$.ajax({
				url: url,
				dataType: "html",
				data: id,
				type: "DELETE",
				async: false,
				success: function(){
					$("#notice").removeClass("alert alert-error alert-success").addClass("alert alert-success");
					$("#notice").html("Items have been removed from your list");
					$("#potluck_list").click();
				},
				error: function(){
					$("#notice").removeClass("alert alert-error alert-success").addClass("alert alert-error");
					$("#notice").html("List category cannot be removed since there are some items that have been rsvped by guests");
				}
			});
			return false;
		});

		$(".editPotluckItems").click(function(){
			var editPotluckItemPath = $(this).attr("href"), editPotluckItemModal = $("#editPotluckItemModal"), url;
			url = editPotluckItemPath.match(/\/events.+/);
			$("#editPotluckItemModal").attr("data-remote", url);
			$.ajax({
				url: url,
				dataType: "html",
				success: function(data){
					editPotluckItemModal.find(".modal-body").html(data);
					editPotluckItemModal.modal("show");
				},
				error: function(xhr, errorText, errorObject){
					editPotluckItemModal.find(".modal-body").html("<div class='alert alert-error'>"+errorText+": Cannot retrieve information for guest. Please contact the administrator about this</div>");
				}
			});
			return false;
		});
	});
</script>

app/views/potluck_items/new.html.erb
<div id="flash_notice"><%= flash[:notice] %></div>
<%= render 'form_new' %>
<script>

	$(document).ready(function(){

		function createPotluckItemObject(item){
			return {"item": $.trim(item), "quantity": 1 };
		}

		$("#submit_button").click(function(){
			var dish_array = [];
			var list_items = $("#list_area").val();
			var url = $("#potluckItemsForm").attr('action');
			var serialized_form;

			$("#flash_notice").removeClass("alert alert-error");
			$("#flash_notice").html("");

			dish_array = $.map(list_items.split(","), function(item, index){
				if ($.trim(item).length > 0)
					return createPotluckItemObject(item);
			});

			$("#potluck_item_dishes").val(JSON.stringify(dish_array));

			serialized_form = $("#potluckItemsForm").serialize();
			$.ajax({
				url: url,
				dataType: "html",
				type: "POST",
				data: serialized_form,
				async: false,
				success: function(data, successText){
					$("#notice").removeClass("alert alert-error alert-success").addClass("alert alert-success");
					$("#notice").html("Items have been created for this event");
					$("#newPotluckItemModal").modal("hide");
				},
				error: function(){
					$("#flash_notice").addClass("alert alert-error");
					$("#flash_notice").html("We couldn't add this potluck category due to the following possible reasons<ul><li>Categories and host quantity need to be present</li><li>Categories need to be unique and items need to be unique per category</li><li>Host quantity needs to be a number</li></ul>");
				}
			});
			return false;
		});

	});

</script>

app/views/potluck_items/show.html.erb
<p id="notice"><%= notice %></p>
<div>
Category: <%= @potluck_item.category %>
</div>
<div>
Dishes: <%= @potluck_item.dishes.join(",") %> 
</div>
<%= link_to 'Edit', edit_event_potluck_item_path(@event, @potluck_item) %> |
<%= link_to 'Back', event_potluck_items_path %>