config/routes.rb
MaximusSamurai::Application.routes.draw do

  devise_for :views

	match 'events/:id/supplemental_info' => 'events#supplemental_info'
	match 'events/:id/supplmenetal_info/edit' => 'events#edit_supplemental_info'
	match 'events/:id/change_location' => 'events#edit_location'
	get 'events/:id/description', :to => 'events#description'
	get 'events/:id/group_email', :to => 'events#group_email'
	get 'events/:id/send_group_email', :to => 'events#send_group_email'
	get 'events/:id/email_host', :to => 'events#email_host'
	get 'events/:id/send_host_email', :to => 'events#send_host_email'
	get 'events/:id/taken_items', :to=>'events#taken_items'
	get 'events/:id/available_items', :to=>'events#available_items'
	get 'events/:id/guests', :to => 'events#guests'
	get 'events/:id/potluck_statistics', :to => 'events#potluck_statistics'
	get 'events/:id/get_host_groups', :to => 'events#get_host_groups'
	delete 'events/:id/remove_from_event/:user_id', :to => 'events#remove_from_event'
	get 'users/:user_id/groups(.:format)', :to => 'groups#index'
	post 'users/:user_id/groups(.:format)',:to => 'groups#create'
	get  'users/:user_id/groups/new(.:format)', :to => 'groups#new'
	get 'users/:user_id/groups/:id(.:format)', :to => 'groups#show'
	get 'users/:user_id/groups/:id/edit(.:format)', :to => 'groups#edit'
	put 'users/:user_id/groups/:id(.:format)', :to => 'groups#update'
	delete 'users/:user_id/groups/:id(.:format)', :to => 'groups#destroy'
	get '/faq', :to => 'events#faq'
	put 'events/:id/change_roles/:attendee_id(.:format)', :to => 'events#change_roles'
	get 'events/:id/export_remaining_items', :to => 'events#export_remaining_items'
	get 'users/:user_id/event_settings(.:format)', :to => 'event_settings#get_settings'
	put 'users/:user_id/event_settings/:id(.:format)', :to => 'event_settings#update_event_settings'
	get '/thank_you', :to => 'attendees#thank_you'

	resources :events do
		get 'attendees/add_attendees', :to => 'attendees#add_attendees'
		post 'attendees/invite_guests', :to => 'attendees#invite_guests'
		get 'attendees/other_guests', :to => 'attendees#other_guests'
		get 'attendees/send_updated_calendar', :to => 'attendees#send_updated_calendar'
		get 'attendees/rsvp', :to => 'attendees#rsvp'
		get 'attendees/:id/send_calendar', :to => 'attendees#send_individual_calendar'
		get 'attendees/:id/email_guest', :to => "attendees#email_guest"
		get 'attendees/:id/send_guest_email', :to => "attendees#send_guest_email"
		get 'suggestions/:id/approve', :to => "suggestions#approve"
		get 'suggestions/:id/reject', :to => "suggestions#reject"
		resources :attendees 
		resources :potluck_items
		resources :suggestions
  end

  devise_for :users
	devise_for :attendees

   root :to => 'events#index'

	devise_scope :user do
  	get "/", :to => 'devise/sessions#new'
  end

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
	before_filter :verify_access, :except => [:thank_you]
	before_filter :verify_host_privileges, :only => [:new, :create, :add_attendees, :invite_guests, :send_updated_calendar, :send_individual_calendar ]
	before_filter :verify_correct_attendee, :only => [:show, :edit, :update, :destroy ]
	before_filter :verify_correct_rsvp, :only => [:rsvp]

  # GET /attendees
  # GET /attendees.json
  def index
		@event = Event.find(params[:event_id])

    respond_to do |format|
      format.html { render :layout => false }# index.html.erb 
      format.json { render json: @attendees }
    end
  end

	def rsvp
		logger.debug "Inside RSVP"
		@event = Event.find(params[:event_id])
		if current_user
			@attendee = Attendee.find_attendee_for(current_user, @event)
		else
			@attendee = get_current_guest
		end
		view = "rsvp"
		if @attendee.rsvp.eql?("No Response")
			view = "initial_rsvp"
		end
		render view, :layout => false
	end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
    @attendee = Attendee.find(params[:id])
		@event = Event.find(params[:event_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/new
  # GET /attendees/new.json
  def new
    @attendee = Attendee.new
		@event = Event.find(params[:event_id])

    respond_to do |format|
      format.html { render :layout => false } # new.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/1/edit
  def edit
    @attendee = Attendee.find(params[:id])
		@event = Event.find(params[:event_id])
		render :layout => false
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(params[:attendee])
		@event = Event.find(params[:event_id])
		@attendee.event_id = @event.id
    respond_to do |format|
      if @attendee.save
				send_message_to(@attendee, current_user)
        format.html { redirect_to [@event,@attendee], notice: 'Attendee was successfully created.' }
        format.json { render json: @attendee, status: :created, location: @attendee }
      else
        format.html { render action: "new", status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendees/1
  # PUT /attendees/1.json
  def update
    @attendee = Attendee.find(params[:id])
		@event = Event.find(params[:event_id])
		@user = User.new
		error_message = String.new

    respond_to do |format|
      if @attendee.update_attributes(params[:attendee])
				if current_user
					if current_user.is_host_for?(@event)
						format.html { render :nothing => true, :status => 204 }
					else
						format.html { redirect_to event_url(@event), notice: 'RSVP was successfully updated.' }
					end
				else
					format.html { redirect_to thank_you_url, notice: 'Thank you for responding!'}
				end
        format.json { head :no_content }
      else
				@attendee.errors.full_messages.each do |message|
					error_message += " #{message}\n,"
				end
				if current_user.is_host_for?(@event)
					format.html { render :nothing => true, status: :unprocessable_entity }
					format.json { render json: @attendee.errors, status: :unprocessable_entity }
				else
					format.html { redirect_to event_url(@event), notice: "RSVP couldn't be updated since it did not receive any of the following responses:#{error_message.chop}" }
					format.json { render json: @attendee.errors, status: :unprocessable_entity }
				end
      end
    end
  end

	def other_guests
		@event = Event.find(params[:event_id])
		if current_user
			@attending = @event.attendees.where("rsvp = 'Going' and (user_id is null or user_id <> ?)", current_user.id)
			@not_going = @event.attendees.where("rsvp = 'Not Going' and (user_id is null or user_id <> ?)", current_user.id)
			@undecided = @event.attendees.where("rsvp = 'Undecided' and (user_id is null or user_id <> ?)", current_user.id)
			@no_response = @event.attendees.where("rsvp = 'No Response' and (user_id is null or user_id <> ?)", current_user.id)
		else
			@attending = @event.attendees.where("rsvp = 'Going' and id <> ?", get_current_guest.id)
			@not_going = @event.attendees.where("rsvp = 'Not Going' and id <> ?", get_current_guest.id)
			@undecided = @event.attendees.where("rsvp = 'Undecided' and id <> ?", get_current_guest.id)
			@no_response = @event.attendees.where("rsvp = 'No Response' and id <> ?", get_current_guest.id)
		end
		render :layout => false
	end

	def add_attendees
		@event = Event.find(params[:event_id])
		render :layout => false
	end

	def email_guest
		@event = Event.find(params[:event_id])
		@attendee = Attendee.find(params[:id])
		render :layout => false
	end

	def thank_you
		@attendee = Attendee.find(session[:attendee_id])
		session[:attendee_id] = nil
		render :layout => false
	end

  def send_guest_email
		@event = Event.find(params[:event_id])
		@subject = params[:subject]
		@body = params[:body]
		@attendee = Attendee.find(params[:id])
		if current_user
			@sender = current_user
		else
			@sender = get_current_guest
		end
		if @subject.blank? || @body.blank?
			flash[:notice] = "You must include both a subject and body"
			render :action => :email_guest, :status => :not_acceptable
		else
			MessageMailer.delay.email_guest(@attendee, @subject, @body, @sender)
			render :action => :email_guest, :status => 200
		end
	end

	def send_updated_calendar
		@event = Event.find(params[:event_id])
		AttendeeMailer.delay.send_updated_calendar(@event)
		render :nothing => true, :status => 200
	end

	def send_individual_calendar
		@attendee = Attendee.find(params[:id])
		@attendee.invite_sent = true
		@attendee.ensure_authentication_token!
		AttendeeMailer.delay.welcome_guest(@attendee, current_user)
		render :nothing => true, :status => 200
	end

	def invite_guests
		@event = Event.find(params[:event_id])
		email_invites = JSON.parse(params[:email_invites])
		@invites = Attendee.invite(email_invites["email"], @event, current_user)
		respond_to do |format|
			format.html { render "invite_guests" }
      format.json  { render json: params[:email_invites] }
    end
	end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee = Attendee.find(params[:id])
		@event = Event.find(params[:event_id])
    @attendee.destroy

    respond_to do |format|
      format.html { render :action => :index }
      format.json { head :no_content }
    end
  end

	protected

	def verify_access
		event = Event.find(params[:event_id])
		logger.debug "session is #{session[:attendee_id]}"
		logger.debug "current_attendee = #{current_attendee}"
		if current_user
			unless current_user.is_host_for?(event) || current_user.belongs_to_event?(event)
				render file: "public/401.html",layout: false, status: :unauthorized
			end
		else
			unless get_current_guest.event_id == event.id
				session[:attendee_id] = nil
				render file: "public/401.html" ,layout: false, status: :unauthorized
			end
		end
	end

	def send_message_to(attendee, inviter)
		unless attendee.email.blank?
			AttendeeMailer.delay.welcome_guest(attendee,inviter)
		end
	end

	def verify_host_privileges
		event = Event.find(params[:event_id])
		unless current_user && current_user.is_host_for?(event)
			render file: "public/422.html", layout: false, status: :unprocessable_entity
		end
	end

	def verify_correct_attendee
		event = Event.find(params[:event_id])
		attendee = Attendee.find(params[:id])
		if current_user
			unless current_user.is_host_for?(event) || attendee.user_id == current_user.id
				render file: "public/422.html", layout: false, status: :unprocessable_entity
			end
		else
			unless get_current_guest.id == attendee.id
				session[:attendee_id] = nil
				render file: "public/422.html", layout: false, status: :unprocessable_entity
			end
		end
	end

	def verify_correct_rsvp
		event = Event.find(params[:event_id])
		if current_user
			attendee = Attendee.find_attendee_for(current_user, event)
		else
			logger.debug "WTF is going on"
			attendee = get_current_guest
		end
		unless attendee
			session[:attendee_id] = nil
			render file: "public/422.html", layout:false, status: :unprocessable_entity
		end
	end
	
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_add_from_groups.html.erb
<div class="row-fluid">
	<div class="span4">
		<ul class="nav nav-pills nav-stacked">
			<% user.groups.each_with_index do |group, index| %>
				<li class="group_name">
					<a><%= group.name %></a>
				</li>
			<% end %>
		</ul>
	</div>
	<div id="email-list-group" class="span6">
	</div>
</div>
<div>
	<button id="importGroupsButton" class="btn btn-primary">Import</button>
</div>
<script>
	$(document).ready(function(){
		var group_map = {};

		function removeActiveClass(){
//			$(".group_name").removeAttr('style');
			$(".group_name").removeClass("active");
		}

		function addClickEventForGroupNames(){
			$(".group_name").each(function(){
				addClickEventForObject($(this));
			});
		}

		function addClickEventForObject(domObject){
				domObject.click(function(){
					var group_name = $.trim(domObject.text());
					removeActiveClass();
//					domObject.attr('style','background-color:skyblue');
					domObject.addClass("active");
					$("#email-list-group").text(group_map[group_name]);
				});
		}

		function populateGroupMap(groups){
			$.each(groups, function(index, group){
				group_map[group.name] = group.email_distribution_list.join(", ");
			});
		}

		function firstSelectChosen(){
			$(".group_name").eq(0).click();
		}

		$.ajax({
			url: window.location.pathname+"/get_host_groups.json",
			dataType: "json",
			type: "GET",
			async: false,
			success: function(groups_json){
				populateGroupMap(groups_json);
				addClickEventForGroupNames();
				firstSelectChosen();
			},
			error: function(){
				alert("Error retrieved while fetching your groups");
			}
		});

		$("#importGroupsButton").click(function(){
			var emailList = $("#email-list-group").text();
			$("#email_area").val(emailList);
			$("#addFromGroupsModal").modal("hide");
		});
	});
</script>

app/views/attendees/_form_edit.html.erb
<%= form_for(@attendee, :url=> [@event,@attendee], :method=>"PUT", :html=>{:id=>"editAttendeeForm"}) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<p>
		<%= f.label :full_name %>
		<%= f.text_field :full_name %>
	</p>

	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>

	<p>
		<%= f.label :rsvp %>
		<%= f.select(:rsvp, options_for_select([["No Response","No Response"],["Undecided","Undecided"],["Going","Going"],["Not Going","Not Going"]]), {}, :onchange => "rsvp();") %>
	</p>
	<div>
			<div><span style="font-weight:bold">Comments? </span><span id="count-down-limit"></span></div>
		<%= f.text_area :comment, :placeholder => "Gonna be five mins late", :style=>"width:35em;height:8em" %>
	</div>
	<div id="guestcount_div">
		<%= f.label :num_of_guests, "Number of guests you are bringing (excluding yourself):" %>
		<%= f.text_field :num_of_guests %>
		<div id="items_box">
			<label>I am bringing </label>
			<div id="items">
			</div>
		</div>
	</div>

  <div>
		<button id="add_items" class="btn btn-success" style="color:white">Add more</button>
		<button id="submit" class="btn btn-primary" style="color:white">Save</button>
  </div>

<% end %>

app/views/attendees/_form_new.html.erb
<%= form_for([@event, @attendee], :method=>"POST", :html=>{:id=>"newAttendeeForm"}) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<p>
		<%= f.label :full_name %>
		<%= f.text_field :full_name %>
	</p>

	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>

	<p>
		<%= f.label :rsvp %>
		<%= f.select :rsvp, [["No Response", "No Response"],["Undecided","Undecided"],["Going","Going"],["Not Going","Not Going"]],{}, :onchange => "rsvp();" %>
	</p>

	<div>
			<div><span style="font-weight:bold">Comments? </span><span id="count-down-limit"></span></div>
		<%= f.text_area :comment, :placeholder => "Gonna be five mins late", :style=>"height:8em;width:35em" %>
	</div>

  <div>
		<button id="new_attendee_submit" class="btn btn-primary" style="color:white">Save</button>
  </div>
<% end %>

app/views/attendees/_nonresponsive_attendee.html.erb
<div class="row" style="vertical-align:-webkit-baseline-middle;text-align:left">
	<div class="span4">
		<% if nonresponsive_attendee.full_name.blank? %><%= nonresponsive_attendee.email %> <% else %><%= nonresponsive_attendee.full_name %> <% end %>
		<% unless nonresponsive_attendee.email.blank? %><%= link_to "", nonresponsive_attendee.event.id.to_s+'/attendees/'+nonresponsive_attendee.id.to_s+'/email_guest', {:style=>"color:blue", :class => "btn btn-link email_individual icon-envelope"} %><% end %>
	</div>
	<div class="span8">
		<p>Comment(s): <% if nonresponsive_attendee.comment.blank? %>None<% else %><%= nonresponsive_attendee.comment %><% end %></p>
	</div>
</div>

app/views/attendees/_unattending_attendee.html.erb
<div class="row" style="vertical-align:-webkit-baseline-middle;text-align:left">
	<div class="span4">
		<% if unattending_attendee.full_name.blank? %><%= unattending_attendee.email %> <% else %><%= unattending_attendee.full_name %> <% end %>
		<% unless unattending_attendee.email.blank? %><%= link_to "", unattending_attendee.event.id.to_s+'/attendees/'+unattending_attendee.id.to_s+'/email_guest', {:style=>"color:blue", :class => "btn btn-link email_individual icon-envelope"} %><% end %>
	</div>
	<div class="span8">
		<p>Comment(s): <% if unattending_attendee.comment.blank? %>None<% else %><%= unattending_attendee.comment %><% end %></p>
	</div>
</div>

app/views/attendees/_undecided_attendee.html.erb
<div class="row" style="vertical-align:-webkit-baseline-middle;text-align:left">
	<div class="span4">
		<% if undecided_attendee.full_name.blank? %><%= undecided_attendee.email %><% else %><%= undecided_attendee.full_name %><% end %>
		<% unless undecided_attendee.email.blank? %><%= link_to "", undecided_attendee.event.id.to_s+'/attendees/'+undecided_attendee.id.to_s+'/email_guest', {:style=>"color:blue", :class => "btn btn-link email_individual icon-envelope"} %><% end %>
	</div>
	<div class="span8">
		<p>Comment(s): <% if undecided_attendee.comment.blank? %>None<% else %><%= undecided_attendee.comment %><% end %></p>
	</div>
</div>

app/views/attendees/add_attendees.html.erb
<%= render :partial=>"add_attendees", :locals => { :event => @event } %>
<script>
  $(document).ready(function(){

		$("#add-distribution-group").click(function(){
			var url = document.location.pathname+"/get_host_groups";
			$("#alert-flash").html();
			$("#alert-flash").removeClass("alert alert-error alert-success");
			$.ajax({
				url: url,
				dataType: "html",
				success: function(data){
					$("#addFromGroupsModal").find(".modal-body").html(data);
					$("#addFromGroupsModal").modal("show");
				},
				error: function(){
					$("#alert-flash").addClass("alert alert-error");
					$("#alert-flash").html("Problems fetching your groups. Please contact your administrator");
				}
			});
			return false;
		});

		$("#send-invitations").click(function(){
			var outputJSON = {};
			var emailArray = [];
			var value = $("#email_area").val();

			if ($.trim(value).length == 0){
				$("#email_area").css('background-color','red');
			} else {
					value = value.replace(/\r|\n/g,"");
					emailArray = value.split(",");
					emailArray = $.map(emailArray, function(data){
					return $.trim(data);
				});
			}

			if ( emailArray.length == 0){
				$("#alert-flash").addClass("alert alert-error");
				$("#alert-flash").text("There are currently no email entries. Please populate them.");
			}
			else {
				outputJSON["email"] = emailArray;
				$("#email_invites").val(JSON.stringify(outputJSON));
				var invite_guest_link = document.location.pathname+"/attendees/invite_guests", serialized_form = $(".form-horizontal").serialize();
				$.ajax({
					url: invite_guest_link,
					type: 'POST',
					data: serialized_form,
					dataType: 'html',
					async: false,
					success: function(data){
						$("#notice").removeClass("alert alert-error alert-success").addClass("alert alert-success");
						$("#notice").html("Invitations have been processed and emails will be sent out to those added to your guest list.");
						$("#guests").click();
					},
					error: function() {
						$(".form-horizontal").prepend("<div class='alert alert-error'>Invitations could not be sent out! Please contact your administrator and describe how to reproduce this issue</div>");
					}
				});
				return false;
			}
		});

		//Need this for the first entry since the others are dynamically added.
		$("#email_area").click(function(){ $(this).css('background-color',''); });
	});
</script>

app/views/attendees/going.html.erb
<%= render :partial => 'events/attending_attendee', :collection => @collection %>

app/views/attendees/invite_guests.html.erb
<h1>Invite Confirmation</h1>
<% if @invites["successful"].length > 0 %>
<div class="alert alert-success">The following emails have been successfully and should be delivered soon:</div>
<div class="row">
<div class="span6 offset2">
<% @invites["successful"].each do |email| %>
	<%= email %>
<% end %>
</div>
</div>
<br/>
<% end %>

<% if @invites["unsuccessful"].length > 0 %>
<div class="alert alert-error">These emails were invalid and could not be sent:</div>
<div class="row">
<div class="span6 offset2">
<% @invites["unsuccessful"].each do |email| %>
	<%= email %>
<% end %>
</div>
</div>
<br/>
<% end %>

<% if @invites["duplicated"].length > 0 %>
<div class="alert alert-info">These emails were already sent out sometime ago: </div>
<div class="row">
<div class="span6 offset2">
<% @invites["duplicated"].each do |email| %>
	<%= email %>
<% end %>
</div>
</div>
<br/>
<% end %>

<%= link_to 'Back To event', @event %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<label for="full_name">Full name: </label>
	<%= @attendee.full_name %>
</p>

<p>
	<label for="email">Email: </label>
	<%= @attendee.email %>
</p>

<p>
	<label for="rsvp">RSVP: </label>
	<%= @attendee.rsvp %>
</p>

<%= link_to 'Edit', edit_event_attendee_url(@event, @attendee) %> |
<%= link_to 'Back', event_attendees_url(@event) %>

app/views/attendees/thank_you.html.erb
<!DOCTYPE html>
<html style="margin: 0;padding: 0;">
<head style="margin: 0;padding: 0;">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" style="margin: 0;padding: 0;">

<title style="margin: 0;padding: 0;">Thank you for using LetsGather</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0" style="margin: 0;padding: 0;">

<%= stylesheet_link_tag 'application','https://fonts.googleapis.com/css?family=Nothing+You+Could+Do|Montserrat+Alternates|Mate' %>

</head>

<body style="margin: 0;padding: 0;background: #ddd;">

<div id="page" style="margin: 0;padding: 2em 0;">

<div class="inner" style="margin: 0 auto;padding: 0;width: 75%;">

<div id="box" style="margin: 60px auto;padding: 2em 1.5em 1em;position: relative;background: #ffffff;-moz-border-radius: 4px;border-radius: 4px;color: rgba(0,0,0, .8);">

<div style="text-align:center"><%= image_tag "LG_Lets_Gather_480.png", alt: "Let's Gather" -%></div>
<div id="invite" style="margin: 0;padding: 0;font-family: 'Nothing You Could Do', cursive;line-height: 1.5;text-align: center;font-size: 2em;margin-top: 30px;margin-bottom: 50px;">
<h1 style="font-size: 2em;margin-bottom: 1.1em">Thank you for using LetsGather!</h1>
<p style="font-family: 'Nothing You Could Do', cursive;line-height: 1.5;text-align: center;font-size: 1.25em">Have a nice rest of the day! Below is your RSVP confirmation:</p>
<div style="margin-top: 1.25em">
<p style="font-family: 'Nothing You Could Do', cursive;line-height: 1.5;text-align: center;font-size: 1em; border: 2px; border-color: lightblue">
	<span style="font-weight:bold">RSVP:</span> <%= @attendee.rsvp %>.<br stye="margin: 0; padding: 0;">
	<span style="font-weight:bold">Number of additional guests you are bringing:</span> <%= @attendee.num_of_guests %>.<br style="margin: 0;padding: 0;">
	<span style="font-weight:bold">Comment: </span><%= @attendee.comment %><br style="margin: 0; padding: 0;">
	<% unless @attendee.dish.blank? %><span style="font-weight:bold">Dishes: </span><br>
		<%= simple_format @attendee.dish.map{ |dish| "#{dish["quantity"]} #{dish["item"]} <span class='label label-info'>#{dish["category"]}</span><br/>"}.join("") %>
	<% end %>
</p>
</div>
</div><!-- end invite -->

</div><!-- end box -->

<div id="RSVP-button" style="margin: 0;padding: 0;margin-top: 40px;text-align: center;">
	<%= link_to 'Create an account', new_user_registration_path, { :style => "margin: 0;padding: 10px 15px;color: #FFF;text-decoration: none;background: #870026;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;border: solid 1px #20538D;font-family: 'Montserrat Alternates', sans-serif;font-size: 21px;text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.4);-webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);-moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);-webkit-transition-duration: 0.2s;-moz-transition-duration: 0.2s;transition-duration: 0.2s;-webkit-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;"} %>
</div><!-- end RSVP-button -->


</div><!-- end inner -->
</div><!-- end page -->

</body>
</html>