config/routes.rb
MaximusSamurai::Application.routes.draw do

  devise_for :views

	match 'events/:id/supplemental_info' => 'events#supplemental_info'
	match 'events/:id/supplmenetal_info/edit' => 'events#edit_supplemental_info'
	match 'events/:id/change_location' => 'events#edit_location'
	get 'events/:id/description', :to => 'events#description'
	get 'events/:id/group_email', :to => 'events#group_email'
	get 'events/:id/send_group_email', :to => 'events#send_group_email'
	get 'events/:id/email_host', :to => 'events#email_host'
	get 'events/:id/send_host_email', :to => 'events#send_host_email'
	get 'events/:id/taken_items', :to=>'events#taken_items'
	get 'events/:id/available_items', :to=>'events#available_items'
	get 'events/:id/guests', :to => 'events#guests'
	get 'events/:id/potluck_statistics', :to => 'events#potluck_statistics'
	get 'events/:id/get_host_groups', :to => 'events#get_host_groups'
	delete 'events/:id/remove_from_event/:user_id', :to => 'events#remove_from_event'
	get 'users/:user_id/groups(.:format)', :to => 'groups#index'
	post 'users/:user_id/groups(.:format)',:to => 'groups#create'
	get  'users/:user_id/groups/new(.:format)', :to => 'groups#new'
	get 'users/:user_id/groups/:id(.:format)', :to => 'groups#show'
	get 'users/:user_id/groups/:id/edit(.:format)', :to => 'groups#edit'
	put 'users/:user_id/groups/:id(.:format)', :to => 'groups#update'
	delete 'users/:user_id/groups/:id(.:format)', :to => 'groups#destroy'
	get '/faq', :to => 'events#faq'
	put 'events/:id/change_roles/:attendee_id(.:format)', :to => 'events#change_roles'
	get 'events/:id/export_remaining_items', :to => 'events#export_remaining_items'
	get 'users/:user_id/event_settings(.:format)', :to => 'event_settings#get_settings'
	put 'users/:user_id/event_settings/:id(.:format)', :to => 'event_settings#update_event_settings'
	get '/thank_you', :to => 'attendees#thank_you'

	resources :events do
		get 'attendees/add_attendees', :to => 'attendees#add_attendees'
		post 'attendees/invite_guests', :to => 'attendees#invite_guests'
		get 'attendees/other_guests', :to => 'attendees#other_guests'
		get 'attendees/send_updated_calendar', :to => 'attendees#send_updated_calendar'
		get 'attendees/rsvp', :to => 'attendees#rsvp'
		get 'attendees/:id/send_calendar', :to => 'attendees#send_individual_calendar'
		get 'attendees/:id/email_guest', :to => "attendees#email_guest"
		get 'attendees/:id/send_guest_email', :to => "attendees#send_guest_email"
		get 'suggestions/:id/approve', :to => "suggestions#approve"
		get 'suggestions/:id/reject', :to => "suggestions#reject"
		resources :attendees 
		resources :potluck_items
		resources :suggestions
  end

  devise_for :users
	devise_for :attendees

   root :to => 'events#index'

	devise_scope :user do
  	get "/", :to => 'devise/sessions#new'
  end

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
	belongs_to :event

	attr_accessible :new_or_existing, :category, :suggested_items, :event_id, :requester_name, :requester_email

	before_validation do |suggestion|
		suggestion.suggested_items = JSON.parse(suggestion.suggested_items) unless suggestion.suggested_items.is_a?(Array)
	end

	serialize :suggested_items
	validates :event_id, :category, :new_or_existing, :requester_name, :requester_email, :presence => true
	validates :new_or_existing, :inclusion => { :in => ["New", "Existing"] , :message => "needs to be submitted with 'New','Existing'" }
	validates :category, :uniqueness => { :scope => :event_id, :message => "should be unique per event and if new list" }, :if => :verify_new_list_prequisities
	validate :verify_new_suggestions_criteria, :if => :verify_new_list_prequisities
	validate :verify_existing_list_criteria, :if => :verify_list_is_existing
	validate :uniqueness_of_suggested_items, :if => :verify_list_is_existing
	validates :suggested_items, :presence => true, :if => :verify_list_is_existing

	def verify_new_suggestions_criteria
		event = self.event
		errors.add(:category, "Category already exists! Please choose another one.") if event.potluck_items.map{|list| list.category.downcase}.include?(self.category)
		verify_no_duplicates_in_suggested_items
	end

	def verify_existing_list_criteria
		potluck_items = self.event.potluck_items.where("category = ?", self.category).first
		available_dishes = potluck_items.dishes.blank? ? [] : potluck_items.dishes.map{|item| item["item"]}
		existing_items = potluck_items.taken_items.map{|i| i["item"] } | available_dishes
		errors.add(:suggested_items, "Suggestion includes items that already exists for the event") unless existing_items.blank? || (existing_items.map{|item| item.downcase} & self.suggested_items.map{|item| item.downcase}).count == 0
		verify_no_duplicates_in_suggested_items
	end

	def uniqueness_of_suggested_items
		current_suggestions = self.event.suggestions.map{|suggestion| suggestion.suggested_items}.flatten
		errors.add(:suggested_items, "Suggestion already contains suggested items from another suggestion") unless ( current_suggestions & self.suggested_items ).count == 0
	end

	def verify_list_is_existing
		return self.new_or_existing.eql?("Existing") && !self.category.blank?
	end

	def verify_new_list_prequisities
		return self.new_or_existing.eql?("New") && !self.category.blank?
	end

	def verify_no_duplicates_in_suggested_items
		errors.add(:suggested_items, "No duplicates items allowed in new list") unless self.suggested_items.map{|item| item.downcase}.uniq.length == self.suggested_items.map{|item| item.downcase}.length
	end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
		before_filter :find_event
		before_filter :verify_access
		before_filter :prohibit_host, :only => [:new, :create]
		before_filter :verify_hosts, :only => [:approve, :reject]
		layout false

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = @event.suggestions
		view = "index"
		unless current_user.is_host_for?(@event)
			view = "readonly_suggestions"
		end

    respond_to do |format|
      format.html { render view } # index.html.erb
      format.json { render json: @suggestions }
    end
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions/new
  # GET /suggestions/new.json
  def new
    @suggestion = Suggestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions/1/edit
  def edit
    @suggestion = Suggestion.find(params[:id])
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(params[:suggestion])
		@suggestion.event_id = @event.id
		@suggestion.requester_name = current_user.full_name
		@suggestion.requester_email = current_user.email

    respond_to do |format|
      if @suggestion.save
				SuggestionMailer.delay.notify_hosts(@suggestion, @event)
        format.html { render :nothing => true, :status => :created, notice: 'Suggestion was successfully created.' }
        format.json { render json: @suggestion, status: :created, location: [@event, @suggestion] }
      else
        format.html { render json: @suggestion.errors, status: :unprocessable_entity }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

	def approve
		@suggestion = Suggestion.find(params[:id])
		@potluck_item = PotluckItem.build_from_suggestion(@suggestion)
		if @potluck_item.save
			SuggestionMailer.delay.approval_email(@suggestion.requester_email, @suggestion.category)
			@suggestion.destroy
			render json: {"count" => @event.suggestions.count}, status: :ok, notice: 'Suggestion was approved'
		else
			render :nothing => true, status: :unprocessable_entity, json: @potluck_item.errors, notice: 'Items from suggestion could not be added to event'
		end
	end

	def reject
		@suggestion = Suggestion.find(params[:id])
		if @suggestion.destroy
			SuggestionMailer.delay.rejection_email(@suggestion.requester_email, @suggestion.category)
			render json: {"count" => @event.suggestions.count}, status: :ok, notice: 'Suggestion was rejected'
		else
			render :nothing => true, status: :unprocessable_entity, notice: 'Suggestion could not be rejected. Please notify your administrator'
		end
	end

  # PUT /suggestions/1
  # PUT /suggestions/1.json
  def update
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      if @suggestion.update_attributes(params[:suggestion])
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion = Suggestion.find(params[:id])
    @suggestion.destroy

    respond_to do |format|
      format.html { redirect_to suggestions_url }
      format.json { head :no_content }
    end
  end

	protected

	def find_event
		@user = current_user
		@event = Event.find(params[:event_id])
	end

	def prohibit_host
		if current_user.is_host_for?(@event)
			render file: "public/401.html" , :formats => [:html], status: :unauthorized and return
		end
	end

	def verify_hosts
		unless current_user.is_host_for?(@event)
			render file: "public/401.html" , :formats => [:html], status: :unauthorized and return
		end
	end

	def verify_access
		unless current_user.is_host_for?(@event) || current_user.belongs_to_event?(@event)
			render file: "public/401.html" , :formats => [:html], status: :unauthorized and return
		end
	end
	
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_existing_template.html.erb
<div class="row">
	<div>
		<span style="font-weight:bold">Category: </span>
			<%= select_tag("existing-category", options_for_select(event.potluck_items.map{|items| [items.category, items.category]})) %>
	</div>
</div>
<div class="row">
	<div id="existing-list">
		<span style="font-weight:bold">Items: </span><textarea style="width:100%" rows="4" placeholder="Enter items here via comma-delimited strings (ex: item1, item2, item3)"></textarea>
	</div>
	<div id="existing-actions">
		<button id="submit-existing-list" class="btn btn-primary">Submit</button>
	</div>
</div>

app/views/suggestions/_form.html.erb
<%= form_for([@event, @suggestion], :html=>{:id=>"suggestionsForm"}) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<p>
		<%= f.text_field :new_or_existing %>
	</p>
	<p>
		<%= f.text_field :category %>
	</p>
	<p>
		<%= f.text_area :suggested_items %>
	</p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestions/_new_suggestion.html.erb
<div class="row">
	<div>
		<span style="font-weight:bold">Category: </span>
		<%= text_field_tag("new-category", nil, :placeholder=>"E.g. Appetizers, boardgames") %>
	</div>
</div>
<div class="row">
	<div id="new-list">
			<span style="font-weight:bold">Items: </span><textarea style="width:100%" rows="4" placeholder="Enter items here via comma-delimited strings (ex: item1, item2, item3)"></textarea>
	</div>
	<div>
		<button id="submit-new-list" class="btn btn-primary">Submit</button>
	</div>
</div>

app/views/suggestions/edit.html.erb
<h1>Editing suggestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<h1>Pending suggestions</h1>
<div id="flash-notice"></div>
<table style="width:100%">
	<thead>
  	<tr>
    	<th>Type</th>
    	<th>Category</th>
			<th>Items</th>
    	<th>Requester</th>
			<th>Options</th>
		</tr>
	</thead>

	<tbody>
<% @suggestions.each do |suggestion| %>
  <tr>
    <td style="text-align:center"><%= suggestion.new_or_existing %></td>
    <td style="text-align:center"><%= suggestion.category %></td>
		<td style="text-align:center"><%= simple_format suggestion.suggested_items.join("<br/>") %></td>
    <td style="text-align:center"><%= suggestion.requester_name %></td>
		<td style="text-align:center"><span class="btn btn-success"><%= link_to " ", {:controller=>:suggestions, :action=>:approve, :event_id => @event.id, :id => suggestion.id}, {:style=>"color:white", :class=>"suggestion-approval icon-ok"} %></span>|<span class="btn btn-danger"><%= link_to " ", {:controller=>:suggestions, :action=>:reject, :event_id => @event.id, :id => suggestion.id}, {:style=>"color:white", :class=>"suggestion-reject icon-remove"} %></span></td>
  </tr>
<% end %>
</tbody>
</table>

<br />
<script>
	$(document).ready(function(){

		function updatePendingCount(count){
			if (count > 0)
				$("#pending_count").html("("+count+")");
			else
				$("#pending_count").empty();
		}

		$(".suggestion-approval").click(function(){
			var url = $(this).attr("href");

			$.ajax({
				url: url,
				dataType: "html",
				success: function(data){
					var parsed = $.parseJSON(data);
					$("#notice").removeClass("alert alert-error alert-success").addClass("alert alert-success");
					$("#notice").html("Items have been added to your event");
					updatePendingCount(parsed.count);
					$("#potluck_list").click();
				},
				error: function(xhr){
					var responseObject = JSON.parse(xhr.responseText), responseText = "List category cannot be added to your event for the following reasons: <ul>";
					for (var key in responseObject){
						responseText += "<li>"+responseObject[key]+"</li>";
					}
					responseText += "</ul> Please contact your event administrator";
					$("#flash-notice").removeClass("alert alert-error alert-success").addClass("alert alert-error");
					$("#flash-notice").html(responseText);
				}
			});
			return false;
		});

		$(".suggestion-reject").click(function(){
			var url = $(this).attr("href");

			$.ajax({
				url: url,
				dataType: "html",
				success: function(data){
					var parsed = $.parseJSON(data);
					$("#notice").removeClass("alert alert-error alert-success").addClass("alert alert-success");
					$("#notice").html("Suggestion has been rejected");
					updatePendingCount(parsed.count);
					$("#pending_suggestions").click();
				},
				error: function(xhr){
					var responseObject = JSON.parse(xhr.responseText), responseText = "Suggestion could not be rejected for the following reasons: <ul>";
					for (var key in responseObject){
						responseText += "<li>"+responseObject[key]+"</li>";
					}
					responseText += "</ul> Please contact your event administrator";
					$("#flash-notice").removeClass("alert alert-error alert-success").addClass("alert alert-error");
					$("#flash-notice").html(responseText);
				}
			});
			return false;
		});
	});
</script>

app/views/suggestions/new.html.erb
<div id="flash_notice"><%= flash[:notice] %></div>
<div class="row">
	<div class="span7">I want to....</div>
</div>
<div class="row">
	<div class="span7">
		<input type="radio" name="type" value="new"><span style="margin-left:1em">Suggest a new list for the party</span><br/>
		<% if @event.potluck_items.count > 0 %>
			<input type="radio" name="type" value="existing"><span style="margin-left:1em">Suggest items for an existing list</span>
		<% end %>
	</div>
</div>

<div class="row" style="margin: 1.5em 0 1.5em 0">
	<div id="new_suggestion" class="span7">
		<%= render 'new_suggestion' %>
	</div>
</div>

<div class="row" style="margin: 1.5em 0 1.5em 0">
	<div id="existing_list" class="span7">
		<%= render :partial => 'existing_template', :locals=>{:event => @event} %>
	</div>
</div>

<div style="display:none">
<%= render 'form' %>
</div>

<script>
	$(document).ready(function(){

		function toggle(typeChosen){
			if (typeChosen == "new"){
				$("#new_suggestion").show();
				$("#existing_list").hide();
			} else {
				$("#new_suggestion").hide();
				$("#existing_list").show();
			}
		}

		function submitForm(){
			var url = $("#suggestionsForm").prop("action"), serialized_form = $("#suggestionsForm").serialize();
			$.ajax({
				url: url,
				dataType: "html",
				type: "POST",
				data: serialized_form,
				async: false,
				success: function(data, successText){
					$("#notice").removeClass("alert alert-error alert-success").addClass("alert alert-success");
					$("#notice").html("Suggestion has been submitted for this event");
					$("#readonly_suggestions").click();
				},
				error: function(xhr){
					$("#flash_notice").addClass("alert alert-error");
					var responseObject = JSON.parse(xhr.responseText);
					var stringResponse = "We cannot submit your suggestion until you address the following: <ul>";
					for (var key in responseObject){
						stringResponse += "<li>"+responseObject[key]+"</li>"
					}
					$("#flash_notice").html(stringResponse+"</ul>");
				}
			});
			return false;
		}

		function addErrorBackgroundFill(element){
			element.css('background-color','red');
		}

		function removeErrorBackgroundFill(element){
			element.css('background-color','');
		}

		function passedValidation(categoryElement, listElement){
			var counter = 0;
			if ($.trim(categoryElement.val()).length == 0){
				addErrorBackgroundFill(categoryElement);
				counter++;
			}
			$.each(listElement.find("textarea"), function(index, elem){
				var list = $(elem).val();
				if ($.trim(list).length == 0){
					addErrorBackgroundFill($(elem));
					counter++;
				}
			});
			return counter == 0;
		}

		function fillInFormForSubmission(type, categoryElement, listElement){
			var category = categoryElement.val(), lists = [];
			if (passedValidation(categoryElement, listElement)) {
				lists = listElement.find("textarea").val().split(",");
				$("form").find("#suggestion_new_or_existing").val(type);
				$("form").find("#suggestion_category").val(category);
				$("form").find("#suggestion_suggested_items").val(JSON.stringify(lists));
				submitForm();
			}
		}

		$("input[type=radio]").change(function(){
			var typeChosen = $(this).val();
			toggle(typeChosen);
		});

		$("input[type=radio]").eq(0).prop("checked",true).change();

		$("#new-category").click(function(){
			removeErrorBackgroundFill($(this));
		});

		$("textarea").click(function(){
			removeErrorBackgroundFill($(this));
		});

		$("#existing-category").change(function(){
			if ($(this).val() == "None"){
				$("#existing-list").hide();
				$("#existing-actions").hide();
			} else {
				$("#existing-list").show();
				$("#existing-actions").show();
			}
		});

		$("#existing-category").trigger("change");

		$("#submit-new-list").click(function(){
			fillInFormForSubmission("New", $("#new-category"), $("#new-list"));
		});

		$("#submit-existing-list").click(function(){
			fillInFormForSubmission("Existing",$("#existing-category"), $("#existing-list"));
		});

	});
</script>

app/views/suggestions/readonly_suggestions.html.erb
<div class="row">
	<div class="span6">
		<h3>New</h3>
		<% if @event.suggestions.select{|suggestion| suggestion.new_or_existing.eql?("New") }.count == 0 %>
			None at the moment
		<% else %>
			<% @event.suggestions.select{|suggestion| suggestion.new_or_existing.eql?("New")}.each do |suggestion| %>
				<span style="font-weight:bold;font-size:1em"><%= suggestion.category %>: </span><%= suggestion.suggested_items.join(",") %><br/>
			<% end %>
		<% end %>
	</div>
</div>
<div class="row">
	<div class="span6">
		<h3>Existing</h3>
		<% if @event.suggestions.select{|suggestion| suggestion.new_or_existing.eql?("Existing") }.count == 0 %>
			None at the moment
		<% else %>
			<% @event.suggestions.select{|suggestion| suggestion.new_or_existing.eql?("Existing")}.each do |suggestion| %>
				<span style="font-weight:bold;font-size:1em"><%= suggestion.category %>: </span><%= suggestion.suggested_items.join(",") %><br/>
			<% end %>
		<% end %>
	</div>
</div>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_event_suggestion_path(@suggestion) %> |
<%= link_to 'Back', event_suggestions_path %>